# Generated by Django 6.0.3 on 2026-03-28 07:06

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Category_Details',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=25, unique=True)),
                ('Category_Photo', models.ImageField(upload_to=api.models.category_pic_path)),
                ('Category_Description', models.CharField(max_length=250)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_category_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL_Customer_Details',
            fields=[
                ('Cust_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')])),
                ('Password', models.CharField(max_length=255)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Building', models.CharField(blank=True, max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=150, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=25, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be exactly 6 digits')])),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'tbl_customer_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL_BookType',
            fields=[
                ('Book_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=250)),
                ('Physical_Book', models.CharField(default='0', max_length=1)),
                ('Audio_Book', models.CharField(default='0', max_length=1)),
                ('E_Book', models.CharField(default='0', max_length=1)),
                ('Video_Book', models.CharField(default='0', max_length=1)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_booktype',
                'ordering': ['Book_ID'],
            },
        ),
    ]
