# Generated by Django 6.0.3 on 2026-04-23 07:47

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_BookType',
            fields=[
                ('Book_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=250)),
                ('Physical_Book', models.CharField(default='0', max_length=1)),
                ('Audio_Book', models.CharField(default='0', max_length=1)),
                ('E_Book', models.CharField(default='0', max_length=1)),
                ('Video_Book', models.CharField(default='0', max_length=1)),
                ('Audio_File', models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path)),
                ('Video_File', models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path)),
                ('E_Book_File', models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_booktype',
                'ordering': ['Book_ID'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Category_Details',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=25, unique=True)),
                ('Category_Photo', models.ImageField(upload_to=api.models.category_pic_path)),
                ('Category_Description', models.CharField(max_length=250)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_category_details',
            },
        ),
        migrations.CreateModel(
            name='TBL_Customer_Details',
            fields=[
                ('Cust_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')])),
                ('Password', models.CharField(max_length=255)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Building', models.CharField(blank=True, max_length=50, null=True)),
                ('Street', models.CharField(blank=True, max_length=150, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Country', models.CharField(blank=True, max_length=25, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be exactly 6 digits')])),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'tbl_customer_details',
            },
        ),
        migrations.CreateModel(
            name='TBL_Employee_Details',
            fields=[
                ('Emp_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_Type', models.CharField(choices=[('1', 'Admin'), ('0', 'Staff')], default='0', max_length=1)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')])),
                ('Password', models.CharField(max_length=15)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Address', models.CharField(max_length=250)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Designation', models.CharField(max_length=25)),
                ('Emp_Photo', models.ImageField(blank=True, null=True, upload_to=api.models.employee_profile_pic_path)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_employee_details',
                'ordering': ['Emp_ID'],
            },
        ),
        migrations.CreateModel(
            name='TBL_MasterOrder_Details',
            fields=[
                ('MasterOrder_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_DateTime', models.DateTimeField(auto_now_add=True)),
                ('T_Quantity', models.IntegerField(default=0)),
                ('T_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Order_Status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('Cust_ID', models.ForeignKey(db_column='Cust_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_customer_details')),
                ('Emp_ID', models.ForeignKey(db_column='Emp_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_employee_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_masterorder_details',
            },
        ),
        migrations.CreateModel(
            name='TBL_Payment',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Mode', models.CharField(max_length=50)),
                ('Payment_Status', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Failed')], default='0', max_length=1)),
                ('MasterOrder_ID', models.ForeignKey(db_column='MasterOrder_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_masterorder_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_payment',
            },
        ),
        migrations.CreateModel(
            name='TBL_Product_Details',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('Publisher', models.CharField(max_length=255)),
                ('Language', models.CharField(blank=True, max_length=50, null=True)),
                ('Number_of_Pages', models.IntegerField(blank=True, null=True)),
                ('Time_Duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField(default=0)),
                ('Product_Description', models.TextField()),
                ('Cover_Photo', models.ImageField(blank=True, null=True, upload_to=api.models.product_photo_path)),
                ('Back_Photo', models.ImageField(blank=True, null=True, upload_to=api.models.product_photo_path)),
                ('IsActive', models.BooleanField(default=True)),
                ('Book_ID', models.ForeignKey(db_column='Book_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_booktype')),
                ('Category_ID', models.ForeignKey(db_column='Category_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_category_details')),
                ('Emp_ID', models.ForeignKey(db_column='Emp_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_employee_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_product',
                'ordering': ['Product_ID'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Order_Details',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('T_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Confirmation', models.CharField(default='1', max_length=1)),
                ('MasterOrder_ID', models.ForeignKey(db_column='MasterOrder_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_masterorder_details')),
                ('Product_ID', models.ForeignKey(db_column='Product_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_product_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_order_details',
            },
        ),
        migrations.CreateModel(
            name='TBL_Feedback_Details',
            fields=[
                ('Feedback_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Rating', models.IntegerField(default=5)),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
                ('Feedback_DateTime', models.DateTimeField(auto_now_add=True)),
                ('Cust_ID', models.ForeignKey(db_column='Cust_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_customer_details')),
                ('Product_ID', models.ForeignKey(db_column='Product_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_product_details')),
            ],
            options={
                'db_table': 'TBL_Feedback_Details',
                'ordering': ['-Feedback_DateTime'],
            },
        ),
        migrations.CreateModel(
            name='TBL_Cart_Details',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Quantity', models.IntegerField()),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cust_ID', models.ForeignKey(db_column='Cust_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_customer_details')),
                ('Product_ID', models.ForeignKey(db_column='Product_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_product_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_cart_details',
            },
        ),
    ]
