# Generated by Django 6.0.3 on 2026-03-28 13:23

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_booktype',
            table='bookapp_tbl_booktype',
        ),
        migrations.CreateModel(
            name='TBL_Product_Details',
            fields=[
                ('Product_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=255)),
                ('Author_Name', models.CharField(max_length=255)),
                ('Publisher_Name', models.CharField(max_length=255)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stock', models.IntegerField(default=0)),
                ('Description', models.TextField()),
                ('Product_Photo', models.ImageField(blank=True, null=True, upload_to=api.models.product_photo_path)),
                ('IsActive', models.CharField(default='1', max_length=1)),
                ('Book_ID', models.ForeignKey(db_column='Book_ID', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_booktype')),
                ('Category_ID', models.ForeignKey(db_column='Category_ID', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_category_details')),
            ],
            options={
                'db_table': 'bookapp_tbl_product',
                'ordering': ['Product_ID'],
            },
        ),
    ]
