# Generated by Django 6.0.3 on 2026-03-28 14:33

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tbl_booktype_table_tbl_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_product_details',
            old_name='Author_Name',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='tbl_product_details',
            old_name='Product_Photo',
            new_name='Back_Photo',
        ),
        migrations.RenameField(
            model_name='tbl_product_details',
            old_name='Description',
            new_name='Product_Description',
        ),
        migrations.RenameField(
            model_name='tbl_product_details',
            old_name='Price',
            new_name='Product_Price',
        ),
        migrations.RenameField(
            model_name='tbl_product_details',
            old_name='Publisher_Name',
            new_name='Publisher',
        ),
        migrations.AddField(
            model_name='tbl_product_details',
            name='Cover_Photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_photo_path),
        ),
        migrations.AddField(
            model_name='tbl_product_details',
            name='Emp_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_product_details',
            name='Language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_product_details',
            name='Number_of_Pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_product_details',
            name='Time_Duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_product_details',
            name='Book_ID',
            field=models.ForeignKey(db_column='Book_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_booktype'),
        ),
        migrations.AlterField(
            model_name='tbl_product_details',
            name='Category_ID',
            field=models.ForeignKey(db_column='Category_ID_id', on_delete=django.db.models.deletion.CASCADE, to='api.tbl_category_details'),
        ),
        migrations.AlterField(
            model_name='tbl_product_details',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
