# Generated by Django 6.0.3 on 2026-04-24 19:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tbl_booktype_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booktype',
            name='Audio_File',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booktype',
            name='E_Book_File',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_booktype',
            name='Video_File',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
