# Generated by Django 6.0.3 on 2026-03-28 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_author_name_tbl_product_details_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Employee_Details',
            fields=[
                ('Emp_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Emp_Type', models.CharField(choices=[('1', 'Admin'), ('0', 'Staff')], default='0', max_length=1)),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=25)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email format')])),
                ('Password', models.CharField(max_length=15)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Address', models.CharField(max_length=250)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Designation', models.CharField(max_length=25)),
                ('Emp_Photo', models.ImageField(blank=True, null=True, upload_to='Employee_Images/')),
                ('IsActive', models.CharField(choices=[('1', 'Active'), ('0', 'Inactive')], default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_employee_details',
                'ordering': ['Emp_ID'],
            },
        ),
        migrations.AlterField(
            model_name='tbl_product_details',
            name='Emp_ID',
            field=models.ForeignKey(db_column='Emp_ID_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.tbl_employee_details'),
            preserve_default=False,
        ),
    ]
