# Generated by Django 6.0.3 on 2026-04-17 19:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tbl_employee_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBL_Cart_Details',
            fields=[
                ('Cart_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Quantity', models.IntegerField()),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'bookapp_tbl_cart_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL_MasterOrder_Details',
            fields=[
                ('MasterOrder_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Order_DateTime', models.DateTimeField(auto_now_add=True)),
                ('T_Quantity', models.IntegerField(default=0)),
                ('T_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Order_Status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'bookapp_tbl_masterorder_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL_Order_Details',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('T_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Confirmation', models.CharField(default='1', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_order_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBL_Payment',
            fields=[
                ('Transaction_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Date', models.DateTimeField(auto_now_add=True)),
                ('Payment_Mode', models.CharField(max_length=50)),
                ('Payment_Status', models.CharField(choices=[('0', 'Pending'), ('1', 'Paid'), ('2', 'Failed')], default='0', max_length=1)),
            ],
            options={
                'db_table': 'bookapp_tbl_payment',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='tbl_booktype',
            name='Audio_File',
            field=models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path),
        ),
        migrations.AddField(
            model_name='tbl_booktype',
            name='E_Book_File',
            field=models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path),
        ),
        migrations.AddField(
            model_name='tbl_booktype',
            name='Video_File',
            field=models.FileField(blank=True, null=True, upload_to=api.models.booktype_file_path),
        ),
        migrations.AlterField(
            model_name='tbl_employee_details',
            name='Emp_Photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.employee_profile_pic_path),
        ),
    ]
