from django.urls import path
from .views import (
    category_list_create,
    category_detail,
    get_categories,
    add_category,
    customer_register,
    login_view,
    employee_login,
    get_book_types,
    add_book_type,
    update_book_type,
    delete_book_type,
    get_products,
    add_product,
    update_product,
    delete_product,
    get_employees,
    add_to_cart, 
    get_cart,
    remove_from_cart,
    update_cart_quantity,
    create_order,
    create_payment,
    get_order_details,
    get_customer,
    get_customer_orders,
    get_all_orders,
    update_order_status,
    get_trending_books,
    dashboard_counts,
    get_low_stock_products,
    get_feedbacks,
    add_feedback,
    soft_delete_feedback,
    get_all_customers,
    deactivate_customer,
    employee_detail,
    get_report_data,
    reset_password_confirm,
    forgot_password_request,
    employee_forgot_password_request,
    employee_reset_password_confirm
)

urlpatterns = [
    path('register/', customer_register),
    path('login/', login_view),
    path('employee-login/', employee_login),
    path('categories/', get_categories),
    path('add-category/', add_category),
    path('category/', category_list_create),
    path('category/<int:id>/', category_detail),
    path('book-types/', get_book_types),
    path('add-book-type/', add_book_type),
    path('book-types/<int:id>/', update_book_type),
    path('delete-book-type/<int:id>/', delete_book_type),
    path("products/", get_products),
    path("add-product/", add_product),
    path("products/<int:id>/", update_product),
    path("delete-product/<int:id>/", delete_product),
    path('employees/', get_employees, name='employees'),
    path('employees/<int:id>/', employee_detail, name='employee_detail'),
    path('cart/add/', add_to_cart),
    path('cart/<int:cust_id>/', get_cart),
    path('cart/remove/<int:cart_id>/', remove_from_cart),
    path('cart/update/<int:cart_id>/', update_cart_quantity),
    path('order/create/', create_order),
    path('payment/create/', create_payment),
    path('order/<int:order_id>/', get_order_details),
    path('customer/<int:cust_id>/', get_customer),
    path('customer/<int:cust_id>/orders/', get_customer_orders),
    path('admin/orders/', get_all_orders),
    path('admin/orders/<int:order_id>/', update_order_status),
    path("admin/trending-books/", get_trending_books),
    path("admin/dashboard-counts/", dashboard_counts),
    path("admin/low-stock/", get_low_stock_products),
    path('feedbacks/', get_feedbacks),
    path("feedback/add/", add_feedback),
    path('feedbacks/<int:feedback_id>/delete/', soft_delete_feedback),
    path('customers/', get_all_customers),
    path('customers/deactivate/<int:cust_id>/', deactivate_customer),
    path('get_report_data/<str:report_type>/', get_report_data),
    path('forgot-password/', forgot_password_request),
    path('reset-password-confirm/', reset_password_confirm),
    path('employee-forgot-password/', employee_forgot_password_request),
    path('employee-reset-password-confirm/', employee_reset_password_confirm),
]